packages:
  - "apps/*"
  - "packages/*"
  - "!packages/n8n-nodes-jkr"
  - "tests/e2e"
allowBuilds:
  '@firebase/util': set this to true or false
  protobufjs: set this to true or false
  unrs-resolver: true
