"""add domain vocabulary and transcript correction events

Revision ID: 744f919d5b3b
Revises: 0dea857b9d77
Create Date: 2026-08-08 17:08:44.890708

Three new tenant-scoped tables for the STT/domain-understanding upgrade:
domain_vocabularies + domain_terms (workspace-owned term lists an agent can
optionally be assigned to, via the new nullable agents.domain_vocabulary_id)
and transcript_correction_events (telemetry — every domain-term correction
the shared conversation engine surfaces, real vs. candidate vs. what was
actually accepted, for future vocabulary curation; not auto-learned).

Row-Level Security applied to all three new tables, mirroring the exact
policy shape from cc55370bda3d_app_role_and_row_level_security.py — new
tables don't inherit RLS automatically and must opt in explicitly.

Note: autogenerate also detected the same two pre-existing, unrelated
missing foreign keys already flagged in 0dea857b9d77 (agents.published_version_id,
knowledge_documents.current_version_id) — deliberately excluded again; that
drift needs its own separately-reviewed migration, not bundled here.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '744f919d5b3b'
down_revision: Union[str, None] = '0dea857b9d77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

RLS_TABLES = ["domain_vocabularies", "domain_terms", "transcript_correction_events"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_vocabularies',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_domain_vocabularies_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain_vocabularies'))
    )
    op.create_index(op.f('ix_domain_vocabularies_workspace_id'), 'domain_vocabularies', ['workspace_id'], unique=False)
    op.create_table('domain_terms',
    sa.Column('vocabulary_id', sa.UUID(), nullable=False),
    sa.Column('canonical', sa.String(length=200), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.String(length=200)), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('criticality', sa.String(length=16), nullable=False),
    sa.Column('languages', postgresql.ARRAY(sa.String(length=16)), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['domain_vocabularies.id'], name=op.f('fk_domain_terms_vocabulary_id_domain_vocabularies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_domain_terms_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain_terms'))
    )
    op.create_index(op.f('ix_domain_terms_vocabulary_id'), 'domain_terms', ['vocabulary_id'], unique=False)
    op.create_index(op.f('ix_domain_terms_workspace_id'), 'domain_terms', ['workspace_id'], unique=False)
    op.create_table('transcript_correction_events',
    sa.Column('call_session_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('domain_term_id', sa.UUID(), nullable=True),
    sa.Column('sequence_index', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('raw_term', sa.String(length=200), nullable=True),
    sa.Column('candidate_term', sa.String(length=200), nullable=True),
    sa.Column('accepted_term', sa.String(length=200), nullable=True),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('correction_method', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('customer_confirmed', sa.Boolean(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_transcript_correction_events_agent_id_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], name=op.f('fk_transcript_correction_events_call_session_id_call_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['domain_term_id'], ['domain_terms.id'], name=op.f('fk_transcript_correction_events_domain_term_id_domain_terms'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_transcript_correction_events_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcript_correction_events'))
    )
    op.create_index(op.f('ix_transcript_correction_events_call_session_id'), 'transcript_correction_events', ['call_session_id'], unique=False)
    op.create_index(op.f('ix_transcript_correction_events_workspace_id'), 'transcript_correction_events', ['workspace_id'], unique=False)
    op.add_column('agents', sa.Column('domain_vocabulary_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_agents_domain_vocabulary_id_domain_vocabularies'), 'agents', 'domain_vocabularies', ['domain_vocabulary_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    for table in RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
              USING (workspace_id = NULLIF(current_setting('app.current_workspace_id', true), '')::uuid);
            """
        )


def downgrade() -> None:
    for table in RLS_TABLES:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table};")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY;")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_agents_domain_vocabulary_id_domain_vocabularies'), 'agents', type_='foreignkey')
    op.drop_column('agents', 'domain_vocabulary_id')
    op.drop_index(op.f('ix_transcript_correction_events_workspace_id'), table_name='transcript_correction_events')
    op.drop_index(op.f('ix_transcript_correction_events_call_session_id'), table_name='transcript_correction_events')
    op.drop_table('transcript_correction_events')
    op.drop_index(op.f('ix_domain_terms_workspace_id'), table_name='domain_terms')
    op.drop_index(op.f('ix_domain_terms_vocabulary_id'), table_name='domain_terms')
    op.drop_table('domain_terms')
    op.drop_index(op.f('ix_domain_vocabularies_workspace_id'), table_name='domain_vocabularies')
    op.drop_table('domain_vocabularies')
    # ### end Alembic commands ###
