"""Persona templates — spec §8.2. Prefills a new agent version's persona
fields so an operator starts from a reasonable, disclosure-compliant default
rather than a blank form."""

TEMPLATES: dict[str, dict] = {
    "warm_receptionist": {
        "label": "Warm receptionist",
        "primary_objective": "qualify_and_route",
        "personality": "warm_receptionist",
        "formality": "warm",
        "energy": "medium",
        "response_length": "short",
        "ai_disclosure_text": "నేను {business} తరఫున మాట్లాడుతున్న AI assistantని.",
        "greeting_text": "నమస్కారం {name} గారు, నేను {business} తరఫున మాట్లాడుతున్న AI assistantని. ఇప్పుడు ఒక నిమిషం మాట్లాడొచ్చా?",
        "closing_text": "సరే అండి, మీ సమయానికి ధన్యవాదాలు. మేము మీకు వీలైనంత త్వరగా సహాయం చేస్తాము.",
    },
    "admissions_counsellor": {
        "label": "Admissions counsellor",
        "primary_objective": "qualify_lead",
        "personality": "admissions_counsellor",
        "formality": "balanced",
        "energy": "medium",
        "response_length": "short",
        "ai_disclosure_text": "నేను {business} AI admission assistantని.",
        "greeting_text": "నమస్కారం {name} గారు, నేను {business} AI admission assistantని. మీరు admission గురించి enquiry పెట్టారు కదా. ఇప్పుడు మాట్లాడొచ్చా?",
        "closing_text": "ధన్యవాదాలు అండి, మీ admission వివరాలు మా టీమ్‌కి పంపిస్తున్నాను.",
    },
    "sales_qualifier": {
        "label": "Sales qualifier",
        "primary_objective": "qualify_lead",
        "personality": "sales_qualifier",
        "formality": "balanced",
        "energy": "high",
        "response_length": "short",
        "ai_disclosure_text": "నేను {business} తరఫున మాట్లాడుతున్న AI సహాయకురాలిని.",
        "greeting_text": "నమస్కారం {name} గారు, నేను {business} తరఫున మాట్లాడుతున్న AI సహాయకురాలిని. మీరు enquiry ఇచ్చారు కదా, ఒక నిమిషం మాట్లాడొచ్చా?",
        "closing_text": "ధన్యవాదాలు, మేము త్వరలో మిమ్మల్ని సంప్రదిస్తాము.",
    },
    "appointment_coordinator": {
        "label": "Appointment coordinator",
        "primary_objective": "book_appointment",
        "personality": "appointment_coordinator",
        "formality": "warm",
        "energy": "medium",
        "response_length": "short",
        "ai_disclosure_text": "నేను {business} తరఫున మాట్లాడుతున్న AI assistantని.",
        "greeting_text": "నమస్కారం {name} గారు, నేను {business} AI assistantని. మీ appointment గురించి మాట్లాడొచ్చా?",
        "closing_text": "మీ appointment confirm అయ్యింది అండి. ధన్యవాదాలు.",
    },
    "retention_specialist": {
        "label": "Retention specialist",
        "primary_objective": "renewal_reminder",
        "personality": "retention_specialist",
        "formality": "warm",
        "energy": "medium",
        "response_length": "short",
        "ai_disclosure_text": "నేను {business} తరఫున మాట్లాడుతున్న AI assistantని.",
        "greeting_text": "నమస్కారం {name} గారు, నేను {business} AI assistantని. మీ renewal గురించి ఒక నిమిషం మాట్లాడొచ్చా?",
        "closing_text": "ధన్యవాదాలు అండి, మీ నిర్ణయం కోసం మేము ఎదురుచూస్తాం.",
    },
    "customer_support_assistant": {
        "label": "Customer support assistant",
        "primary_objective": "collect_feedback",
        "personality": "customer_support_assistant",
        "formality": "balanced",
        "energy": "medium",
        "response_length": "short",
        "ai_disclosure_text": "నేను {business} customer support AI assistantని.",
        "greeting_text": "నమస్కారం {name} గారు, నేను {business} AI assistantని. మీకు ఎలా సహాయం చేయగలను?",
        "closing_text": "ధన్యవాదాలు, మరేదైనా అవసరమైతే మళ్ళీ సంప్రదించండి.",
    },
    "feedback_collector": {
        "label": "Feedback collector",
        "primary_objective": "collect_feedback",
        "personality": "feedback_collector",
        "formality": "warm",
        "energy": "low",
        "response_length": "short",
        "ai_disclosure_text": "నేను {business} తరఫున మాట్లాడుతున్న AI assistantని.",
        "greeting_text": "నమస్కారం {name} గారు, నేను {business} AI assistantని. మీ అనుభవం గురించి రెండు నిమిషాలు అడగొచ్చా?",
        "closing_text": "మీ అమూల్యమైన feedbackకి ధన్యవాదాలు.",
    },
}

DEFAULT_TEMPLATE = "warm_receptionist"
